Add the parameter "properties" to Trace
eclipse-cdt-cloud/trace-server-protocol pull request #106
Opened 2024-09-25 15:04 UTC by siwei-zhang-work

Add the parameter "properties" introduced by commit 499408e3979cab403a5d58 in the server (incubator).

Link to the PR for the commit: [eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator#79](https://github.com/eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator/pull/79)

2024-10-03 13:54 UTC, PatrickTasse reviewed
I'm not sure why this happens or if it can be prevented, but the order of properties of all existing elements has been shuffled, making this very hard to review. I think we were able to avoid this before, but I don't remember.

2024-10-03 17:13 UTC, bhufmann commented
> I'm not sure why this happens or if it can be prevented, but the order of properties of all existing elements has been shuffled, making this very hard to review. I think we were able to avoid this before, but I don't remember.

Yes, that happens to me too. One factor in how it is generated is the version of swagger. What I've been doing is that I do a manual diff and only copy the new parts or change parts that I know I updated. Maybe we need a commit that generates the existing swagger and then create a commit with the actual changes.

2024-10-03 17:14 UTC, bhufmann commented on API-proposed.yaml
I think you removed manually added proposed APIs in this file. These changes should remain.

2024-10-03 17:15 UTC, bhufmann requested changes
as per previous comment

2024-10-30 15:34 UTC, bhufmann commented
replaced by #107

2024-10-30 15:34 UTC, closed without merging