Add Bookmark endpoints specifications and update TSP version to 0.3.0
eclipse-cdt-cloud/trace-server-protocol pull request #112
Opened 2024-11-22 17:56 UTC by kavehshahedi

The specifications of newly introduced endpoints for managing bookmarks of experiments are added to the API.yaml and API-proposed.yaml. Also, TSP version is udpated to 0.3.0 from 0.2.0.

2024-11-22 18:53 UTC, bhufmann requested changes

2024-11-22 18:53 UTC, bhufmann commented on API.yaml
> +- name: Bookmarks
I think you added it manually and it's generated by the server definitions. See comment here: https://github.com/eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator/pull/102#pullrequestreview-245536650

Please update the server PR for that.

2024-11-22 18:53 UTC, bhufmann commented on API-proposed.yaml
> +  description: Bookmark areas of interest in the experiment.
Move Bookmark up after line 34 to match the API.yaml file.

2024-11-22 19:46 UTC, bhufmann approved these changes
Looks good to me. Thanks for the contribution!

2024-11-25 21:46 UTC, MatthewKhouzam approved these changes
In a later version, I would like a notes field that can populate tooltips.

2024-11-26 15:10 UTC, merged