Add APIs for XY specific attributes for XY Entries
eclipse-cdt-cloud/trace-server-protocol pull request #85
Opened 2023-01-10 21:18 UTC by bhufmann

- Added XYTreeEntry: it extends TreeDataModel and adds XY specific attributes. Currently, the optional flag 'isDefault' is added to indicate that entry should be checked and its xy data should be drawn by default
- Added XYTreeEntryModel: it extends TreeEntryModel and returns a list of XyTreeEntry instead
- Updated XYTreeResponse: it returns a XYTreeEntryModel now

Contributes to https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/786

Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>

2023-01-12 20:47 UTC, marco-miller requested changes
LGTM, and verified using [the corresponding server patch](https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/199321) locally.

Just a nit, in the commit message (and PR description), `XyTreeEntry` should read `XYTreeEntry` (with a capital `Y`).

2023-01-13 17:51 UTC, marco-miller requested changes

2023-01-13 17:51 UTC, marco-miller commented on API-proposed.yaml
> +          default:
Became `isDefault:` AFAIK indeed.

2023-01-13 17:51 UTC, marco-miller commented on API.yaml
> +          default:
Same as above.

2023-01-13 20:32 UTC, marco-miller approved these changes
LGTM, thanks again.

2023-01-13 20:39 UTC, MatthewKhouzam approved these changes
LGTM

2023-01-13 20:40 UTC, merged